CREATE DATABASE IF NOT EXISTS dashboard;

USE dashboard;

CREATE TABLE IF NOT EXISTS top ( 
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    METRIC VARCHAR(255) NOT NULL,
    PRODUCT VARCHAR(255) NOT NULL,
    EXPOSED DOUBLE NOT NULL,
    CONTROL DOUBLE NOT NULL,
    UPLIFT DOUBLE NOT NULL,
    PCT_UPLIFT DOUBLE NOT NULL
);

LOAD DATA LOCAL INFILE 'data/top.csv'
INTO TABLE top
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(METRIC, PRODUCT, EXPOSED, CONTROL, UPLIFT, PCT_UPLIFT);