CREATE DATABASE dashboard;

USE dashboard;

CREATE TABLE top ( 
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    METRIC VARCHAR(255) NOT NULL,
    PRODUCT VARCHAR(255) NOT NULL,
    EXPOSED DOUBLE NOT NULL,
    CONTROL DOUBLE NOT NULL,
    UPLIFT DOUBLE NOT NULL,
    PCT_UPLIFT DOUBLE NOT NULL
)